### ISSUE TITLE
对应微云的图片集链接失效了，能否再发一下，链接都尝试过了

### ISSUE THREAD

**Issue by koala9527** [asyncins/captcha_cnn#2]
https://share.weiyun.com/5l3pMZu  https://share.weiyun.com/513pMZu 都失效了

**Comment by new-cainiao** [comment]
+1

**Comment by asyncins** [comment]
> https://share.weiyun.com/5l3pMZu https://share.weiyun.com/513pMZu 都失效了

新上传的，百度网盘链接: https://pan.baidu.com/s/1LoQTK51RHbdXSrJ0o8uxqA  密码: tl5i
